### ISSUE TITLE
"No such file or directory" error in Mandos go Test

### ISSUE THREAD

**Issue by newtmex** [multiversx/mx-sdk-rs#803]
I tried running this test https://github.com/ElrondNetwork/elrond-wasm-rs/blob/886ea0e953c700da74cc0693ab04e7d0d30c52b5/contracts/examples/multisig/tests/multisig_mandos_go_test.rs#L2 with the `mandos-go-tests` feature enabled and got the error "No such file or directory".

I am experiencing this in my contract (the file exists and relative path is correct), so I tried this one here and got same error.

Is there some other config I have to set or there's a bug?

**Comment by Milou6** [comment]
I'm experiencing the same problem. Tried running the test for a default template adder smart-contract, both in my local machine and in an erdpy virtual-env, and I always get the same error when running `erdpy contract test`:

```
INFO:projects.core:run_tests.project: /home/emile/GeneZys/testing/smart_contracts/adder
INFO:myprocess:run_process: ['/home/emile/elrondsdk/vmtools/mandos-test', '/home/emile/GeneZys/testing/smart_contracts/adder/mandos'], in folder: None
Traceback (most recent call last):
  File "/home/emile/elrondsdk/erdpy-venv/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/cli.py", line 29, in main
    _do_main()
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/cli.py", line 55, in _do_main
    args.func(args)
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/cli_contracts.py", line 288, in run_tests
    projects.run_tests(args)
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/projects/core.py", line 66, in run_tests
    project.run_tests(directory, wildcard)
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/projects/project_base.py", line 137, in run_tests
    myprocess.run_process(args, env=tool_env)
  File "/home/emile/elrondsdk/erdpy-venv/lib64/python3.10/site-packages/erdpy/myprocess.py", line 19, in run_process
    output = subprocess.check_output(args, shell=False, universal_newlines=True, stderr=subprocess.STDOUT, env=env, cwd=cwd)
  File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/emile/elrondsdk/vmtools/mandos-test'

```

Indeed, my elrondsdk folder doesn't have any `mandos-test` folder, only a `mx-chain-vm-go-1.4.60` folder with `mandos-go` inside. Any help appreciated.

**Comment by andrei-marinica** [comment]
Hi!
Looks like there was a misconfiguration, the VM tools were not installed.
Closing this, since the code is also very old, we have had several releases of the framework and mxpy(formerly erdpy).
Please reopen if issues persist with the newer versions.
